### ISSUE TITLE
1.8: synccopy --config config.yaml doesn't work

### ISSUE THREAD

**Issue by PascalSl** [Azure/blobxfer#100]
STR:
Create/USE a synccopy YAML config file that works in 1.7.1

Use that same YAML file in 1.8 using the command

`blobxfer synccopy --config config.yml`

Result:
```
Traceback (most recent call last):
  File "cli\cli.py", line 1164, in <module>
  File "site-packages\click\core.py", line 764, in __call__
  File "site-packages\click\core.py", line 717, in main
  File "site-packages\click\core.py", line 1137, in invoke
  File "site-packages\click\core.py", line 956, in invoke
  File "site-packages\click\core.py", line 555, in invoke
  File "site-packages\click\decorators.py", line 64, in new_func
  File "site-packages\click\core.py", line 555, in invoke
  File "cli\cli.py", line 1133, in synccopy
  File "cli\settings.py", line 220, in add_cli_options
ValueError: --remote-path not specified
[24296] Failed to execute script cli
```

Expected:
Should work as in previous versions

Didn't try for upload or download, might be similar there.

**Comment by alfpark** [comment]
This has been fixed in `develop`, please provide feedback if this fixes your issue.

**Comment by rnsc** [comment]
hello @alfpark, I compiled develop and tested your changes, it looks good.
No more error on synccopy with a yaml config only.
