### ISSUE TITLE
Upload with --skip-on-md5-match hangs (Windows)

### ISSUE THREAD

**Issue by dommorin** [Azure/blobxfer#104]
#### Azure blobxfer parameters output
```
============================================
         Azure blobxfer parameters
============================================
         blobxfer version: 1.9.0
                 platform: Windows-10-10.0.18362-SP0
               components: CPython=3.7.2-64bit azstor.blob=2.0.1 azstor.file=2.0.1 crypt=2.7 req=2.22.0
       transfer direction: local -> Azure
                  workers: disk=64 xfer=96 md5=20 crypto=0
                 log file: C:\Users\domorin\AppData\Local\Temp\tmp8ai2f3rf
                  dry run: False
              resume file: None
                  timeout: connect=10 read=200 max_retries=1000
                     mode: StorageModes.Auto
                  skip on: fs_match=False lmt_ge=False md5=True
                   delete: extraneous=False only=False
                overwrite: True
                recursive: True
            rename single: False
         strip components: 0
              access tier: None
         chunk size bytes: 0
           one shot bytes: 0
         store properties: attr=False cc='' ct=<mime> md5=False
           rsa public key: None
       local source paths: C:\git\philly-tools\examples\mnist_pytorch\src
============================================
Traceback (most recent call last):
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\domorin\AppData\Local\Continuum\miniconda3\envs\pt\Scripts\blobxfer.exe\__main__.py", line 9, in <module>
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\click\core.py", line 555, in invoke
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\blobxfer_cli\cli.py", line 1143, in upload
    ctx.general_options, ctx.credentials, spec
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\blobxfer\operations\upload.py", line 1283, in start
    raise ex
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\blobxfer\operations\upload.py", line 1270, in start
    self._run()
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\blobxfer\operations\upload.py", line 1131, in _run
    num_workers=self._general_options.concurrency.md5_processes)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\blobxfer\operations\md5.py", line 126, in __init__
    super().__init__(self._worker_process, num_workers, 'MD5')
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\blobxfer\models\offload.py", line 60, in __init__
    self._initialize_processes(target, num_workers, description)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\site-packages\blobxfer\models\offload.py", line 96, in _initialize_processes
    proc.start()
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle weakref objects
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "c:\users\domorin\appdata\local\continuum\miniconda3\envs\pt\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```

#### Steps to Reproduce
blobxfer upload --storage-account mystorage --local-path C:/path/to/my/local/data --progress-bar --log-file C:\Users\me\AppData\Local\Temp\tmpa2zv1qwq --remote-path container/target/path **--skip-on-md5-match**

#### Expected Results
Upload the directory to blob storage.

#### Actual Results
The console hangs. The process does not return on "EOFError: Ran out of input" and the data is not uploaded.

**Comment by alfpark** [comment]
As a temporary mitigation to unblock, please specify the argument: `--md5-processes 1`

**Comment by alfpark** [comment]
After further investigation, this seems to only affect Python 3.7 due to a behavior change: https://bugs.python.org/issue34034
