### ISSUE TITLE
azure.common.AzureConflictHttpError: The blob type is invalid for this operation. ErrorCode: InvalidBlobType

### ISSUE THREAD

**Issue by krezreb** [Azure/blobxfer#118]
#### Problem Description

I am transferring between two containers in two storage accounts and getting the error message 

```azure.common.AzureConflictHttpError: The blob type is invalid for this operation. ErrorCode: InvalidBlobType```

#### Azure blobxfer parameters output
```
============================================
         Azure blobxfer parameters
============================================
         blobxfer version: 1.9.4
                 platform: Linux-5.4.0-26-generic-x86_64-with-glibc2.29
               components: CPython=3.8.2-64bit azstor.blob=2.1.0 azstor.file=2.1.0 crypt=2.8 req=2.22.0
       transfer direction: Azure -> Azure
                  workers: disk=0 xfer=32 md5=0 crypto=0
                 log file: None
                  dry run: True
              resume file: None
                  timeout: connect=10 read=200 max_retries=1000
              source mode: StorageModes.Auto
                dest mode: StorageModes.Auto
         server side copy: True
                  skip on: fs_match=False lmt_ge=False md5=True
                   delete: extraneous=True only=False
                overwrite: True
                recursive: True
            rename single: False
         strip components: 2
              access tier: None
============================================
```

#### Steps to Reproduce

My blobxfer command:

```
export SRC_CONTAINER=a
export SRC_PATH=app1/data
export DEST_CONTAINER=b

blobxfer synccopy \
--server-side-copy --progress-bar --delete \
--skip-on-md5-match \
--overwrite \
--remote-path $SRC_CONTAINER/$SRC_PATH \
--storage-account $SRC_STORAGE_ACCOUNT \
--sync-copy-dest-storage-account  $DEST_STORAGE_ACCOUNT \
--sync-copy-dest-remote-path $DEST_CONTAINER \
--strip-components 2  
```

#### Expected Results

Files should copy

#### Actual Results

This stack trace:

```
2020-04-24 14:32:14.008 INFO - blobxfer start time: 2020-04-24 14:32:14.008000+02:00
2020-04-24 14:32:14.008 DEBUG - spawning 32 transfer threads
2020-04-24 14:32:21.520 ERROR - The blob type is invalid for this operation. ErrorCode: InvalidBlobType
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobType</Code><Message>The blob type is invalid for this operation.
RequestId:9dd75d9a-001e-009b-6634-1afae6000000
Time:2020-04-24T12:32:21.4904759Z</Message></Error>
Traceback (most recent call last):
  File "/home/jbeeson/.local/lib/python3.8/site-packages/blobxfer/operations/synccopy.py", line 917, in start
    self._run()
  File "/home/jbeeson/.local/lib/python3.8/site-packages/blobxfer/operations/synccopy.py", line 853, in _run
    self._add_to_transfer_queue(src_ase, dst_ase)
  File "/home/jbeeson/.local/lib/python3.8/site-packages/blobxfer/operations/synccopy.py", line 250, in _add_to_transfer_queue
    bl = blobxfer.operations.azure.blob.block.get_committed_block_list(
  File "/home/jbeeson/.local/lib/python3.8/site-packages/blobxfer/operations/azure/blob/block.py", line 223, in get_committed_block_list
    return ase.client.get_block_list(
  File "/home/jbeeson/.local/lib/python3.8/site-packages/azure/storage/blob/blockblobservice.py", line 335, in get_block_list
    return self._perform_request(request, _convert_xml_to_block_list)
  File "/home/jbeeson/.local/lib/python3.8/site-packages/azure/storage/common/storageclient.py", line 446, in _perform_request
    raise ex
  File "/home/jbeeson/.local/lib/python3.8/site-packages/azure/storage/common/storageclient.py", line 374, in _perform_request
    raise ex
  File "/home/jbeeson/.local/lib/python3.8/site-packages/azure/storage/common/storageclient.py", line 359, in _perform_request
    _http_error_handler(
  File "/home/jbeeson/.local/lib/python3.8/site-packages/azure/storage/common/_error.py", line 115, in _http_error_handler
    raise ex
azure.common.AzureConflictHttpError: The blob type is invalid for this operation. ErrorCode: InvalidBlobType
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidBlobType</Code><Message>The blob type is invalid for this operation.
RequestId:9dd75d9a-001e-009b-6634-1afae6000000
```

#### Additonal Comments

- both storage accounts are StorageV2 with  Hierarchical Namespace enabled
- There's no information about which blob is causing the error, nor why.
- when I do `--dry-run` the files list correctly
- The absence or presence of `--progress-bar --delete --skip-on-md5-match --overwrite ` doesn't change the result
- I destroyed and recreated the destination container, no change
- Many of the filenames in the source have special characters in them, but they are all UTF8, I assume this is not the cause of the problem

**Comment by ValentinB10** [comment]
+1

**Comment by alfpark** [comment]
Can you please re-run with `--enable-azure-storage-logger --transfer-threads 1`? This will let you know which blob is problematic. Please post the relevant log portion if applicable. Additionally, indicate what type of blob it is, naming, and any special properties it may have.
