### ISSUE TITLE
The MAC signature found in the HTTP request '' is not the same as any computed signature

### ISSUE THREAD

**Issue by prerakpradhan** [Azure/blobxfer#12]
Hey,
I was trying to use Blobxfer to upload files from Azure Batch into Azure storage. I installed blobxfer with the following commands:
apt-get install -y build-essential libssl-dev libffi-dev python-dev python3-dev
pip3 install azure-storage blobxfer

I am trying to upload to storage with the command:
blobxfer <storagename> logs file.txt --storageaccountkey <storageKey>

I keep getting the following error:
blocks/min    Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/blobxfer.py", line 967, in run
    offset, bytestoxfer, encparam, flock, filedesc)
  File "/usr/local/lib/python3.4/dist-packages/blobxfer.py", line 1121, in put_storage_data
    timeout=self.args.timeout)
  File "/usr/local/lib/python3.4/dist-packages/blobxfer.py", line 1444, in azure_request
    return req(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/blob/blockblobservice.py", line 175, in put_block
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/blob/blockblobservice.py", line 848, in _put_block
    self._perform_request(request)
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/storageclient.py", line 266, in _perform_request
    raise ex
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/storageclient.py", line 238, in _perform_request
    raise ex
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/storageclient.py", line 225, in _perform_request
    _http_error_handler(HTTPError(response.status, response.message, response.headers, response.body))
  File "/usr/local/lib/python3.4/dist-packages/azure/storage/_error.py", line 98, in _http_error_handler
    raise AzureHttpError(message, http_error.status)
azure.common.AzureHttpError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:83bb9646-0001-0038-0c1c-418916000000
Time:2016-11-17T21:51:00.6168829Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'Mb41HpCZ438MVNPXMDDMqaUyEy20MSYb2XAGHnwoxNw=' is not the same as any computed signature. Server used following string to sign: 'PUT

It did work initially but on subsequent tries it keeps giving me this error. Any help with this would be appreciated.

**Comment by alfpark** [comment]
@prerakpradhan You're missing a required positional parameter in this command:

```
blobxfer logs file.txt --storageaccountkey
```

Ensure your storage account key is correct and you're not incorrectly pasting (you can put the key in quotes as well).

**Comment by prerakpradhan** [comment]
ahh sorry my bad, i seemed to have forgotten to put in the storage account name here. I did try it with the storage account name and it still was giving me the same error. The key was copy pasted so that wasn't it. It seems like something in my environment setup was causing this. I tried it again in a new environment except this time used pip instead of pip3 and it all seemed to work again. :)
