### ISSUE TITLE
Better progress indication for computing skip dictionary

### ISSUE THREAD

**Issue by lediur** [Azure/blobxfer#33]
I'm running into an issue where blobxfer takes a very long time to start up (i.e. it sits for a long time after showing the `script start time` message for upwards of 15 minutes), and it seems like it's trying to list all of the files in the remote container according to the traceback:

```
Traceback (most recent call last):
  File "/home/derrick/.local/bin/blobxfer", line 11, in <module>
    sys.exit(main())
  File "/home/derrick/.local/lib/python2.7/site-packages/blobxfer.py", line 2361, in main
    blobskipdict = get_blob_listing(blob_service[0], args)
  File "/home/derrick/.local/lib/python2.7/site-packages/blobxfer.py", line 1637, in get_blob_listing
    for blob in result:
  File "/home/derrick/.local/lib/python2.7/site-packages/azure/storage/models.py", line 112, in __iter__
    resources = self._list_method(*self._list_args, **self._list_kwargs)
  File "/home/derrick/.local/lib/python2.7/site-packages/azure/storage/blob/baseblobservice.py", line 1275, in _list_blobs
    return self._perform_request(request, _convert_xml_to_blob_list, operation_context=_context)
  File "/home/derrick/.local/lib/python2.7/site-packages/azure/storage/storageclient.py", line 234, in _perform_request
    return parser(response)
  File "/home/derrick/.local/lib/python2.7/site-packages/azure/storage/blob/_deserialization.py", line 299, in _convert_xml_to_blob_list
    setattr(blob.properties, info[1], info[2](property_element.text))
  File "/home/derrick/.local/lib/python2.7/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/derrick/.local/lib/python2.7/site-packages/dateutil/parser.py", line 556, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/home/derrick/.local/lib/python2.7/site-packages/dateutil/parser.py", line 675, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/home/derrick/.local/lib/python2.7/site-packages/dateutil/parser.py", line 192, in split
    return list(cls(s))
  File "/home/derrick/.local/lib/python2.7/site-packages/dateutil/parser.py", line 188, in next
    return self.__next__()  # Python 2.x support
  File "/home/derrick/.local/lib/python2.7/site-packages/dateutil/parser.py", line 181, in __next__
    token = self.get_token()
  File "/home/derrick/.local/lib/python2.7/site-packages/dateutil/parser.py", line 82, in get_token
    if self.tokenstack:
KeyboardInterrupt
```

This very long startup time is mitigated if I provide the `--no-skiponmatch` option, so it seems like it's trying to get all of the MD5s to skip on. I have many files (100k+) in the container, so this process does take quite a while.

Perhaps there should be a progress indicator for this, or some kind of heuristic that only fetches the skiplist MD5s for files that are found in the include / source directory? Some documentation about this edge case might also be useful.

**Comment by alfpark** [comment]
As you have figured out, the root cause is due to collecting MD5s to do comparisons to skip. This behavior is fundamentally changing in 1.0.0 and there will no longer be long blocking behavior in these cases (see #23).

**Comment by alfpark** [comment]
1.0.0a4 has been released which eliminates this blocking behavior.
