### ISSUE TITLE
Script Fail on download

### ISSUE THREAD

**Issue by HogarthEng164** [Azure/blobxfer#36]
Hi There.
When downloading from azure using blobxfer
I have these errors.

Traceback (most recent call last):
  File "/usr/local/bin/blobxfer", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/blobxfer.py", line 2566, in main
    localfile, blob, False, blobdict[blob])
  File "/usr/local/lib/python2.7/dist-packages/blobxfer.py", line 1786, in generate_xferspec_download
    remoteresource = encode_blobname(args, remoteresource)
  File "/usr/local/lib/python2.7/dist-packages/blobxfer.py", line 1524, in encode_blobname
    return urlquote(blobname)
  File "/usr/lib/python2.7/urllib.py", line 1288, in quote
    return ''.join(map(quoter, s))
KeyError: u'\u2560'
hwwadm@hgslhpsv01:/m

The blobs I'm restoring were happily uploaded to Azure using blobxfer, so were happy with all the filenames.

DD_15Fischsta╠łbchen_450g.ai

This is the filename that caused the blobxfer to stop, however Azure Storage Explorer was happy to download, so dealt with this odd character. I've also had issues with ( ) in filenames - renaming them by removing the brackets fixes the issues.

Looking froward to hearing from you!

many thanks.

**Comment by alfpark** [comment]
Is it possible to install blobxfer for Python3 on your system?

**Comment by alfpark** [comment]
Closing due to no response.
