### ISSUE TITLE
--skip-on-filesize-match option causes Traceback.

### ISSUE THREAD

**Issue by olivelawn** [Azure/blobxfer#51]
Using latest blobxfer-1.0.0rc2-linux-x86_64 linux binary.  I get a traceback with the --skip-on-filesize-match, but seems to work when that option is not supplied.

```
> [root@vdev-azw-ecom-us-nfs001 ~]# ./blobxfer-1.0.0rc2-linux-x86_64 upload --skip-on-filesize-match --delete --log-file /tmp/blobxfer.log --progress-bar --storage-account blahblablah --storage-account-key IHeMfulLFR/M5COcyVvNRjw9+Z3CIFpgPVQ7EdODEEnTU2ZHDfnCckblahblahblah --remote-path test --local-path /etc/yum/
============================================
         Azure blobxfer parameters
============================================
         blobxfer version: 1.0.0rc2
                 platform: Linux-3.10.0-514.28.1.el7.x86_64-x86_64-with-redhat-7.3-Maipo
               components: CPython=3.5.3 azstor.blob=0.36.0 azstor.file=0.36.0 crypt=2.1.1 req=2.18.4
       transfer direction: local -> Azure
                  workers: disk=4 xfer=8 md5=0 crypto=0
                 log file: /tmp/blobxfer.log
              resume file: None
                  timeout: connect=3.1 read=12.1
                     mode: StorageModes.Auto
                  skip on: fs_match=True lmt_ge=False md5=False
        delete extraneous: True
                overwrite: True
                recursive: True
            rename single: False
         chunk size bytes: 0
           one shot bytes: 0
         strip components: 0
         store properties: attr=False md5=False
           rsa public key: None
       local source paths: /etc/yum
============================================
Traceback (most recent call last):
  File "cli/cli.py", line 906, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 64, in new_func
  File "site-packages/click/core.py", line 535, in invoke
  File "cli/cli.py", line 901, in upload
  File "blobxfer/operations/upload.py", line 1145, in start
  File "blobxfer/operations/upload.py", line 1117, in _run
RuntimeError: upload mismatch: [count=0/-7 bytes=0/-1884]
[40227] Failed to execute script cli
[root@vdev-azw-ecom-us-nfs001 ~]#
[root@vdev-azw-ecom-us-nfs001 ~]# ./blobxfer-1.0.0rc2-linux-x86_64 upload --delete --log-file /tmp/blobxfer.log --progress-bar --storage-account blahblah --storage-account-key IHeMfulLFR/M5COcyVvNRjw9+Z3CIFpgPVQ7EdODEEnTU2Zblahblahblah --remote-path test --local-path /etc/yum/
============================================
         Azure blobxfer parameters
============================================
         blobxfer version: 1.0.0rc2
                 platform: Linux-3.10.0-514.28.1.el7.x86_64-x86_64-with-redhat-7.3-Maipo
               components: CPython=3.5.3 azstor.blob=0.36.0 azstor.file=0.36.0 crypt=2.1.1 req=2.18.4
       transfer direction: local -> Azure
                  workers: disk=4 xfer=8 md5=0 crypto=0
                 log file: /tmp/blobxfer.log
              resume file: None
                  timeout: connect=3.1 read=12.1
                     mode: StorageModes.Auto
                  skip on: fs_match=False lmt_ge=False md5=False
        delete extraneous: True
                overwrite: True
                recursive: True
            rename single: False
         chunk size bytes: 0
           one shot bytes: 0
         strip components: 0
         store properties: attr=False md5=False
           rsa public key: None
       local source paths: /etc/yum
============================================
upload progress: [>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 100.00%        0.009 MiB/sec, 7/7 uploaded
[root@vdev-azw-ecom-us-nfs001 ~]#
```

**Comment by alfpark** [comment]
Does this happen with `--skip-on-md5-match` (assuming you have MD5 stored server side) and/or `--skip-on-lmt-ge`?

**Comment by alfpark** [comment]
Does not happen with md5 match but with lmt_ge and filesize match.

**Comment by alfpark** [comment]
@olivelawn if you are able to use the `alfpark/blobxfer:develop` Docker image, please let me know if this resolves your issue.
