### ISSUE TITLE
UnicodeEncodeError: 'utf-8' codec can't encode character

### ISSUE THREAD

**Issue by olivelawn** [Azure/blobxfer#54]
blobxfer is barfing after running on a fairly large directory tree.  I'm not sure if it dislikes certain filename on the source side, or if this is a bug.  Any thoughts?

```
         blobxfer version: 1.0.0rc3
                 platform: Linux-3.10.0-327.4.5.el7.x86_64-x86_64-with-centos-7.2.1511-Core
               components: CPython=3.6.3 azstor.blob=0.36.0 azstor.file=0.36.0 crypt=2.1.2 req=2.18.4
       transfer direction: local -> Azure
                  workers: disk=32 xfer=64 md5=0 crypto=0
                 log file: /var/log/blobxfer.log
              resume file: None
                  timeout: connect=3.1 read=12.1
                     mode: StorageModes.Auto
                  skip on: fs_match=True lmt_ge=False md5=False
        delete extraneous: True
                overwrite: True
                recursive: True
            rename single: False
         chunk size bytes: 0
           one shot bytes: 0
         strip components: 0
         store properties: attr=False md5=False
           rsa public key: None
       local source paths: /mnt/Asset_Archive
============================================
2017-11-06 13:54:35.921 INFO - blobxfer start time: 2017-11-06 13:54:35.921523-05:00
2017-11-06 13:54:35.921 DEBUG - spawning 32 disk threads
2017-11-06 13:54:35.950 DEBUG - spawning 64 transfer threads
2017-11-06 20:44:37.756 ERROR - 'utf-8' codec can't encode character '\udca0' in position 74: surrogates not allowed
Traceback (most recent call last):
  File "blobxfer/operations/upload.py", line 1156, in start
  File "blobxfer/operations/upload.py", line 1064, in _run
  File "blobxfer/operations/upload.py", line 1063, in <listcomp>
  File "blobxfer/operations/upload.py", line 898, in _generate_destination_for_source
  File "blobxfer/operations/upload.py", line 842, in _check_for_existing_remote
  File "blobxfer/operations/azure/blob/__init__.py", line 83, in get_blob_properties
  File "site-packages/azure/storage/blob/baseblobservice.py", line 1453, in get_blob_properties
  File "site-packages/azure/storage/common/storageclient.py", line 231, in _perform_request
  File "site-packages/azure/storage/common/_serialization.py", line 83, in _update_request
  File "urllib/parse.py", line 781, in quote
UnicodeEncodeError: 'utf-8' codec can't encode character '\udca0' in position 74: surrogates not allowed
```

**Comment by alfpark** [comment]
Please upgrade to blobxfer 1.0.0 and then re-run with the flag `--enable-azure-storage-logger`. You will be able to see the request/file that is making blobxfer error. You'll need to rename that file to something the utf8 codec can handle.

**Comment by alfpark** [comment]
Closing, please re-open if you feel this hasn't been resolved.
