### ISSUE TITLE
Errors out (memory) when uploading 200 x 1GB files

### ISSUE THREAD

**Issue by seguler** [Azure/blobxfer#59]
2018-02-05 06:19:22.623 INFO -

         Azure blobxfer parameters

         blobxfer version: 1.1.1
                 platform: Windows-10-10.0.14393-SP0
               components: CPython=3.6.4 azstor.blob=1.0.0 azstor.file=1.0.0 crypt=2.1.4 req=2.18.4
       transfer direction: local -> Azure
                  workers: disk=32 xfer=64 md5=0 crypto=0
                 log file: None
              resume file: None
                  timeout: connect=3.1 read=12.1
                     mode: StorageModes.Auto
                  skip on: fs_match=False lmt_ge=False md5=False
        delete extraneous: False
                overwrite: True
                recursive: True
            rename single: False
              access tier: None
         chunk size bytes: 0
           one shot bytes: 0
         strip components: 0
         store properties: attr=False md5=False
           rsa public key: None
       local source paths: F:\dir3
============================================
2018-02-05 06:19:22.638 INFO - blobxfer start time: 2018-02-05 06:19:22.638958+00:00
2018-02-05 06:19:22.638 DEBUG - spawning 32 disk threads
2018-02-05 06:19:22.670 DEBUG - spawning 64 transfer threads
2018-02-05 06:19:23.941 INFO - created blob container 200 on storage account sdksampleperftest
2018-02-05 06:19:59.422 DEBUG - 0 files 0.0000 MiB filesize and/or lmt_ge skipped
2018-02-05 06:19:59.423 DEBUG - 199 local/remote files processed, waiting for upload completion of approx. 203776.0000 MiB
2018-02-05 06:19:59.423 ERROR - exceptions encountered while uploading
2018-02-05 06:19:59.423 ERROR -
Traceback (most recent call last):
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\blobxfer\operations\upload.py", line 1167, in start
    self._run()
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\blobxfer\operations\upload.py", line 1132, in _run
    raise self._exceptions[0]
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\blobxfer\operations\upload.py", line 456, in _worker_thread_upload
    self._process_upload_descriptor(ud)
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\blobxfer\operations\upload.py", line 564, in _process_upload_descriptor
    data, newoffset = ud.read_data(offsets)
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\blobxfer\models\upload.py", line 934, in read_data
    data = fd.read(offsets.num_bytes)
MemoryError
Traceback (most recent call last):
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\seguler\AppData\Local\Programs\Python\Python36-32\Scripts\blobxfer.exe\__main__.py", line 9, in <module>
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\blobxfer_cli\cli.py", line 977, in upload
    ctx.general_options, ctx.credentials, spec
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\blobxfer\operations\upload.py", line 1167, in start
    self._run()
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\blobxfer\operations\upload.py", line 1132, in _run
    raise self._exceptions[0]
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\blobxfer\operations\upload.py", line 456, in _worker_thread_upload
    self._process_upload_descriptor(ud)
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\blobxfer\operations\upload.py", line 564, in _process_upload_descriptor
    data, newoffset = ud.read_data(offsets)
  File "c:\users\seguler\appdata\local\programs\python\python36-32\lib\site-packages\blobxfer\models\upload.py", line 934, in read_data
    data = fd.read(offsets.num_bytes)
MemoryError

**Comment by alfpark** [comment]
Most likely this is due to using a 32-bit version of Python. Can you try with the 64-bit interpreter?

**Comment by alfpark** [comment]
Closing due to no response. Please re-open if you are still encountering this issue.
