### ISSUE TITLE
UnboundLocalError: local variable 'last_consecutive' referenced before assignment

### ISSUE THREAD

**Issue by dsemarketer** [Azure/blobxfer#60]
When uploading a 49mb file, this error happens. I'm able to upload smaller (14mb and less) files without issue.

```
2018-02-20 16:49:47.232 INFO -
============================================
         Azure blobxfer parameters
============================================
         blobxfer version: 1.1.1
                 platform: Linux-4.4.0-104-generic-x86_64-with-debian-8.10
               components: CPython=3.6.3 azstor.blob=1.0.0 azstor.file=1.0.0 crypt=2.1.4 req=2.18.4
       transfer direction: local -> Azure
                  workers: disk=4 xfer=8 md5=0 crypto=0
                 log file: None
              resume file: resume.db
                  timeout: connect=3.1 read=12.1
                     mode: StorageModes.Auto
                  skip on: fs_match=False lmt_ge=False md5=False
        delete extraneous: False
                overwrite: True
                recursive: True
            rename single: False
              access tier: None
         chunk size bytes: 0
           one shot bytes: 0
         strip components: 0
         store properties: attr=False md5=False
           rsa public key: None
       local source paths: the.file.name
============================================
2018-02-20 16:49:47.233 INFO - blobxfer start time: 2018-02-20 16:49:47.233438+00:00
2018-02-20 16:49:47.260 DEBUG - spawning 4 disk threads
2018-02-20 16:49:47.275 DEBUG - spawning 8 transfer threads
2018-02-20 16:49:47.460 DEBUG - no resume record for container/the.file.name
2018-02-20 16:49:47.462 DEBUG - 0 files 0.0000 MiB filesize and/or lmt_ge skipped
2018-02-20 16:49:47.462 DEBUG - 1 local/remote files processed, waiting for upload completion of approx. 49.8319 MiB
2018-02-20 16:49:48.229 ERROR - exceptions encountered while uploading
2018-02-20 16:49:48.229 ERROR - local variable 'last_consecutive' referenced before assignment
Traceback (most recent call last):
  File "blobxfer/operations/upload.py", line 1167, in start
  File "blobxfer/operations/upload.py", line 1132, in _run
  File "blobxfer/operations/upload.py", line 353, in _worker_thread_transfer
  File "blobxfer/operations/upload.py", line 381, in _process_transfer
  File "blobxfer/models/upload.py", line 585, in complete_offset_upload
UnboundLocalError: local variable 'last_consecutive' referenced before assignment
Traceback (most recent call last):
  File "cli/cli.py", line 982, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 64, in new_func
  File "site-packages/click/core.py", line 535, in invoke
  File "cli/cli.py", line 977, in upload
  File "blobxfer/operations/upload.py", line 1167, in start
  File "blobxfer/operations/upload.py", line 1132, in _run
  File "blobxfer/operations/upload.py", line 353, in _worker_thread_transfer
  File "blobxfer/operations/upload.py", line 381, in _process_transfer
  File "blobxfer/models/upload.py", line 585, in complete_offset_upload
UnboundLocalError: local variable 'last_consecutive' referenced before assignment
[340] Failed to execute script cli
```

And then if I retry, (resume file present) I get this error:

```
2018-02-20 16:53:57.151 INFO -
============================================
         Azure blobxfer parameters
============================================
         blobxfer version: 1.1.1
                 platform: Linux-4.4.0-104-generic-x86_64-with-debian-8.10
               components: CPython=3.6.3 azstor.blob=1.0.0 azstor.file=1.0.0 crypt=2.1.4 req=2.18.4
       transfer direction: local -> Azure
                  workers: disk=4 xfer=8 md5=0 crypto=0
                 log file: None
              resume file: resume.db
                  timeout: connect=3.1 read=12.1
                     mode: StorageModes.Auto
                  skip on: fs_match=False lmt_ge=False md5=False
        delete extraneous: False
                overwrite: True
                recursive: True
            rename single: False
              access tier: None
         chunk size bytes: 0
           one shot bytes: 0
         strip components: 0
         store properties: attr=False md5=False
           rsa public key: None
       local source paths: the.file.name
============================================
2018-02-20 16:53:57.153 INFO - blobxfer start time: 2018-02-20 16:53:57.153239+00:00
2018-02-20 16:53:57.156 DEBUG - spawning 4 disk threads
2018-02-20 16:53:57.181 DEBUG - spawning 8 transfer threads
2018-02-20 16:53:57.227 DEBUG - 0 files 0.0000 MiB filesize and/or lmt_ge skipped
2018-02-20 16:53:57.227 DEBUG - 1 local/remote files processed, waiting for upload completion of approx. 49.8319 MiB
2018-02-20 16:53:57.228 DEBUG - container/the.file.name upload already completed
2018-02-20 16:53:57.233 ERROR - exceptions encountered while uploading
2018-02-20 16:53:57.233 ERROR - 'Descriptor' object has no attribute '_src_ase'
Traceback (most recent call last):
  File "blobxfer/operations/upload.py", line 1167, in start
  File "blobxfer/operations/upload.py", line 1132, in _run
  File "blobxfer/operations/upload.py", line 456, in _worker_thread_upload
  File "blobxfer/operations/upload.py", line 503, in _process_upload_descriptor
  File "blobxfer/models/upload.py", line 891, in next_offsets
  File "blobxfer/models/upload.py", line 820, in _resume
AttributeError: 'Descriptor' object has no attribute '_src_ase'
Traceback (most recent call last):
  File "cli/cli.py", line 982, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 64, in new_func
  File "site-packages/click/core.py", line 535, in invoke
  File "cli/cli.py", line 977, in upload
  File "blobxfer/operations/upload.py", line 1167, in start
  File "blobxfer/operations/upload.py", line 1132, in _run
  File "blobxfer/operations/upload.py", line 456, in _worker_thread_upload
  File "blobxfer/operations/upload.py", line 503, in _process_upload_descriptor
  File "blobxfer/models/upload.py", line 891, in next_offsets
  File "blobxfer/models/upload.py", line 820, in _resume
AttributeError: 'Descriptor' object has no attribute '_src_ase'
[357] Failed to execute script cli
```

**Comment by dsemarketer** [comment]
I suspect it has something to do with this issue:

https://github.com/Azure/azure-batch-samples/issues/43

> There could be a lot of causes for this problem, but most likely the uncommitted block list on storage is in a state that will no longer work with the script. You will need to do one of the following: (1) perform a GetBlockList (with blocklisttype=uncommitted) to retrieve the uncommitted block list, commit the block list, then delete the blob, (2) create a dummy blob (can be of length zero) with the same blob name in the same container and transfer it using a non-blocked transfer, (3) wait 7 days for the uncommitted block list to garbage collect.
