### ISSUE TITLE
Error: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 28: ordinal not in range(128)

### ISSUE THREAD

**Issue by ksaye** [Azure/blobxfer#64]
Using the command:  blobxfer upload --verbose --file-md5 --skip-on-md5-match --storage-account-key "E7Lm5IREMOVEDGBcYQ==" --no-progress-bar --rsa-public-key /etc/cert.pem --storage-account kevinsaybackup --remote-path ksaye700t --local-path /samba/externalDisk/

I get the error below:

OS:
Linux ksaye-700T 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

version:
root@ksaye-700T:~# blobxfer --version
blobxfer, version 1.1.1

2018-04-07 18:28:07,238 DEBUG blobxfer.operations.md5:_worker_process:151 pre-transfer MD5 check: G3KAF9i12zRakAZ/4XC2eQ== <L..R> G3KAF9i12zRakAZ/4XC2eQ== /samba/externalDisk/data/P/drivers/cdrom/Neroe5.5/Player/Setup.cfg
2018-04-07 18:28:07,271 ERROR blobxfer.operations.upload:start:1174 'ascii' codec can't decode byte 0xe2 in position 28: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/upload.py", line 1167, in start
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/upload.py", line 1079, in _run
    create_destination_id(ase._client, ase.container, ase.name)
  File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/upload.py", line 185, in create_destination_id
    return ';'.join((client.primary_endpoint, container, name))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 28: ordinal not in range(128)
2018-04-07 18:28:07,496 DEBUG blobxfer.operations.md5:_worker_process:151 pre-transfer MD5 check: h3u3LZgX7cfVm/Rwe1Zt2w== <L..R> h3u3LZgX7cfVm/Rwe1Zt2w== /samba/externalDisk/data/P/drivers/cdrom/Neroe5.5/Player/Setup.exe
2018-04-07 18:28:08,180 DEBUG blobxfer.operations.md5:_worker_process:151 pre-transfer MD5 check: YA7Aq07rdrkiZpMO7GWSLA== <L..R> YA7Aq07rdrkiZpMO7GWSLA== /samba/externalDisk/data/P/drivers/cdrom/Neroe5.5/FreeDB/FreeDB.zip
Traceback (most recent call last):
  File "/usr/local/bin/blobxfer", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/blobxfer_cli/cli.py", line 977, in upload
    ctx.general_options, ctx.credentials, spec
  File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/upload.py", line 1167, in start
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/upload.py", line 1079, in _run
    create_destination_id(ase._client, ase.container, ase.name)
  File "/usr/local/lib/python2.7/dist-packages/blobxfer/operations/upload.py", line 185, in create_destination_id
    return ';'.join((client.primary_endpoint, container, name))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 28: ordinal not in range(128)

**Comment by alfpark** [comment]
It looks like you have installed blobxfer for python2.7. Since you are using Ubuntu 16.04, it is recommended to [install blobxfer for Python3](https://github.com/Azure/blobxfer/blob/master/docs/01-installation.md#ubuntu).

If you wish to continue using blobxfer on Python2 (not recommended), your locale may not be set properly. You can either set your locale to be unicode-aware or set the environment variable `PYTHONIOENCODING`, e.g.:

```shell
PYTHONIOENCODING=utf-8 blobxfer ...
```

Or export that variable.

**Comment by alfpark** [comment]
Closing, please re-open if this doesn't solve your issue.
