### ISSUE TITLE
python no module error

### ISSUE THREAD

**Issue by psychicindian** [Azure/blobxfer#9]
could you please help

`(azure)[ec2-user@stagingadmin blobxfer] pip freeze | grep azure
azure-common==1.1.4
azure-nspkg==1.0.0
azure-servicemanagement-legacy==0.20.5
azure-storage==0.33.0

(azure)[ec2-user@stagingadmin blobxfer] ./blobxfer.py -h
Traceback (most recent call last):
  File "./blobxfer.py", line 72, in <module>
    import azure.common
ImportError: No module named common

(azure)[ec2-user@admin blobxfer] blobxfer
Traceback (most recent call last):
  File "/media/ebs/karthikk_src/azure/bin/blobxfer", line 9, in <module>
    load_entry_point('blobxfer==0.12.0', 'console_scripts', 'blobxfer')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 542, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2569, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2229, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2235, in resolve
  File "build/bdist.linux-x86_64/egg/blobxfer.py", line 72, in <module>
ImportError: No module named common
(azure)[ec2-user@admin blobxfer] which blobxfer
/media/ebs/karthikk_src/azure/bin/blobxfer`

**Comment by alfpark** [comment]
@psychicindian 
Please answer the following:
1. Are you running in a virtualenv?
2. What is your OS (distribution and version)?
3. What is your version of Python (`python --version`)?

You can try the following to isolate blobxfer from your system:
```
virtualenv bx
source bx/bin/activate
pip install blobxfer
blobxfer -h
```

**Comment by psychicindian** [comment]
thanks. pip install blobxfer works fine

1.yes
2.mac os sierra 10.12
3.python 2.7.10

**Comment by alfpark** [comment]
@psychicindian does this mean your issue is resolved?

**Comment by psychicindian** [comment]
Yes, marking the issue as closed
