### ISSUE TITLE
SSLWantWriteError not iterable

### ISSUE THREAD

**Issue by sordonia** [Azure/blobxfer#98]
Hi,

We're seeing this error randomly appearing on blobxfer upload.
Is that something you already saw ?

Thanks,

Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\http\client.py", line 1065, in _send_output
    self.send(chunk)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\http\client.py", line 986, in send
    self.sock.sendall(data)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\ssl.py", line 972, in sendall
    v = self.send(byte_view[count:])
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\ssl.py", line 941, in send
    return self._sslobj.write(data)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\ssl.py", line 642, in write
    return self._sslobj.write(data)
ssl.SSLWantWriteError: The operation did not complete (write) (_ssl.c:2138)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='polozovphillyblob.blob.core.windows.net', port=443): Max retries exceeded with url: /spider/data%5C.vector_cache%5Cglove.42B.300d.txt.pt?comp=block&blockid=MDAwMDAwMDA%3D (Caused by SSLError(SSLWantWriteError(3, 'The operation did not complete (write) (_ssl.c:2138)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\azure\storage\common\storageclient.py", line 321, in _perform_request
    response = self._httpclient.perform_request(request)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\azure\storage\common\_http\httpclient.py", line 92, in perform_request
    proxies=self.proxies)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='polozovphillyblob.blob.core.windows.net', port=443): Max retries exceeded with url: /spider/data%5C.vector_cache%5Cglove.42B.300d.txt.pt?comp=block&blockid=MDAwMDAwMDA%3D (Caused by SSLError(SSLWantWriteError(3, 'The operation did not complete (write) (_ssl.c:2138)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\azure\storage\common\storageclient.py", line 361, in _perform_request
    raise _wrap_exception(ex, AzureException)
azure.common.AzureException: HTTPSConnectionPool(host='polozovphillyblob.blob.core.windows.net', port=443): Max retries exceeded with url: /spider/data%5C.vector_cache%5Cglove.42B.300d.txt.pt?comp=block&blockid=MDAwMDAwMDA%3D (Caused by SSLError(SSLWantWriteError(3, 'The operation did not complete (write) (_ssl.c:2138)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\blobxfer\operations\upload.py", line 1240, in start
    self._run()
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\blobxfer\operations\upload.py", line 1203, in _run
    raise self._exceptions[0]
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\blobxfer\operations\upload.py", line 364, in _worker_thread_transfer
    self._process_transfer(ud, ase, offsets, data)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\blobxfer\operations\upload.py", line 381, in _process_transfer
    self._put_data(ud, ase, offsets, data)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\blobxfer\operations\upload.py", line 429, in _put_data
    ase, offsets, data)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\blobxfer\operations\azure\blob\block.py", line 126, in put_block
    timeout=timeout)  # noqa
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\azure\storage\blob\blockblobservice.py", line 186, in put_block
    timeout=timeout
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\azure\storage\blob\blockblobservice.py", line 1143, in _put_block
    self._perform_request(request)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\azure\storage\common\storageclient.py", line 409, in _perform_request
    retry_interval = self.retry(retry_context)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\blobxfer\retry.py", line 195, in retry
    return self._retry(context, self._backoff)
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\azure\storage\common\retry.py", line 144, in _retry
    if self._should_retry(context):
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\blobxfer\retry.py", line 143, in _should_retry
    if any(x in msg for x in _RETRYABLE_ERRNO_MAXRETRY):
  File "c:\program files (x86)\microsoft visual studio\shared\python36_64\lib\site-packages\blobxfer\retry.py", line 143, in <genexpr>
    if any(x in msg for x in _RETRYABLE_ERRNO_MAXRETRY):
TypeError: argument of type 'SSLWantWriteError' is not iterable

**Comment by alfpark** [comment]
Is this a transient error? If you retry does it succeed?

Also, please post the full blobxfer parameter output and commandline (redacted).
